### ISSUE TITLE
ISO URL for Windows 10 in the packer template is returning a 403 error

### ISSUE THREAD

**Issue by j00c3** [nickzer0/RedLab#3]
When running packer with the windows10.json file, the ISO URL in the template results in a 403 error.

```
==> vmware-iso: Trying https://software.download.prss.microsoft.com/db/Win10_21H2_English_x64.iso?checksum=md5%3A823c3cb59ff0fd43272f12bb2e3a089d&e=1647515032&h=ca02b7026b799096cf3bfa06623b669e3de08ae5a1222b946f6cd25dba0a2807&t=c827a38d-c632-48a5-85f7-b15f00531ee6
==> vmware-iso: Download failed bad response code: 403
==> vmware-iso: error downloading ISO: [bad response code: 403]
Build 'vmware-iso' errored after 1 second 773 milliseconds: error downloading ISO: [bad response code: 403]
```

**Comment by nickzer0** [comment]
Thanks for raising the issue. It looks like the token expires in the URL after a certain period of time. There's not much I can do to get around that outside of hosting the ISO somewhere, so I'll just issue some guidance on how to find the URL for the ISO manually to update it.

**Comment by nickzer0** [comment]
This actually looks like an issue with MS servers not playing well, you can see more [here](https://github.com/hashicorp/packer/issues/11568), but can't find a fix at this moment.

**Comment by nickzer0** [comment]
OK I found a workaround, if you run the ISO URL through a URL shortener it works. I'll update the main readme.
